import type { Topic } from "../../../types/topic";

const topic: Topic = {
  id: "animal_shelter_animal_of_the_week",
  title: "Tierheimtier der Woche",
  keywords: ["Tierheimtier", "Tierheim"],
  podcast: [
    {
      number: 196,
      episode: "Werwolf Syndrom",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/196-werwolf-syndrom-q5qmkz4aol7wd",
      timecode: 0,
      airDate: "2024-12-12",
      context: "Ridgeback-Mix Chuma",
    },
    {
      number: 194,
      episode: "Akani, Igelnot & Gerichtsurteil",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/194-akani-igelnot-ein-gerichtsurteil-rtb0827raqywx",
      timecode: 0,
      airDate: "2024-11-28",
      context: "Schwein Norbert",
    },
    {
      number: 186,
      episode: "Tierwohl paradox",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/186-tierwohl-paradox-kpxqn1g2q73xu",
      timecode: 0,
      airDate: "2024-10-03",
    },
    {
      number: 185,
      episode: "Genug ist genug",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/185-genug-ist-genug-lh5uilbydwhba",
      timecode: 0,
      airDate: "2024-09-26",
      context: "ein fröhlicher Schäferhund",
    },
    {
      number: 184,
      episode: "Wo ist Wilma?",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/184-wo-ist-wilma-7hen4hjz2wbam",
      timecode: 0,
      airDate: "2024-09-19",
      context: "Rüde Chips",
    },
    {
      number: 182,
      episode: "Blümerle",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/182-bluemerle-wwapqiaojdbki",
      timecode: 0,
      airDate: "2024-09-05",
      context: "freundlicher Mischling Leo",
    },
    {
      number: "Summer Edition #10",
      episode: "Stabile Typen",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-10-stabile-typen-4s4s3dlg5jjyi",
      timecode: 0,
      airDate: "2024-08-29",
      context: "schöne Katze Emma",
    },
    {
      number: "Summer Edition #9",
      episode: "Katzengefühle",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-9-katzengefuehle-57gluk24bflht",
      timecode: 0,
      airDate: "2024-08-22",
      context:
        "der 14 jährige Charly - ein Traumhund fürs Sofa und Spaziergänge",
    },
    {
      number: "Summer Edition #8",
      episode: "Die schlauesten Tiere der Welt",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-8-die-schlauesten-tiere-der-welt-febovvjxrpps9",
      timecode: 0,
      airDate: "2024-08-15",
      context: "ein Notfall",
    },
    {
      number: "Summer Edition #7",
      episode: "Hobby Horsing for Olympia!",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-7-hobby-horsing-for-olympia-7pbpazh2zvi72",
      timecode: 0,
      airDate: "2024-08-08",
      context:
        "„Colt“, das Tierheimtier der Woche, ein typischer Rassevertreter",
    },
    {
      number: "Summer Edition #6",
      episode: "Junger Mann zum Mitreisen gesucht!",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-6-junger-mann-zum-mitreisen-gesucht-oxv9o45d8w0ad",
      timecode: 0,
      airDate: "2024-08-01",
      context: "ein sehr anschmiegsamer Windhund aus einem Shelter in Bukarest",
    },
    {
      number: "Summer Edition #4",
      episode: "Koerper kraeftig, aber nicht ohne Adel",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-4-koerper-kraeftig-aber-nicht-ohne-adel-zjwmcmhv4vzuh",
      timecode: 0,
      airDate: "2024-07-18",
      context: "bildschöne Manali aus dem Tierheim Troisdorf",
    },
    {
      number: "Summer Edition #2",
      episode: "Sommernostalgie und Bahnärger",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-2-sommernostalgie-und-bahnaerger-0fne38y8v7soe",
      timecode: 0,
      airDate: "2024-07-04",
      context: "Ludwig und Tofu",
    },
    {
      number: "Summer Edition #1",
      episode: "Geburtstag, Good News",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/summer-edition-1-geburtstag-good-news-8jh3dh6u48lpr",
      timecode: 0,
      airDate: "2024-06-27",
      context: "„Strolch“ von den Notfellchen Rumänien",
    },
    {
      number: 166,
      episode: "Zwingerclub",
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/166-zwingerclub-2ok8zkm2k969d",
      timecode: 0,
      airDate: "2024-05-16",
      context: "neue Rubrik: Tierheimtier der Woche",
    },
  ],
};

export default topic;
