export const AMOUNT_OF_BREEDS_APPROVED = 346;
export const AMOUNT_OF_BREEDS_PROVISIONAL = 16;
export const AMOUNT_OF_BREEDS_REMOVED = 14;
export const AMOUNT_OF_BREEDS_TOTAL =
  AMOUNT_OF_BREEDS_APPROVED + AMOUNT_OF_BREEDS_PROVISIONAL;
