import type { Topic } from "../../../types/topic";

const topic: Topic = {
  id: "guests",
  title: "Gäst:innen",
  keywords: ["Gast", "Gäste", "Gäste:innen"],
  podcast: [
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/192-was-ist-eigentlich-hoopers-agility-0njifnzinmuz1",
      number: 192,
      episode: "Was ist eigentlich Hoopers Agility?",
      timecode: 0,
      context: "zu Gast: Ramona Houscht",
      airDate: "2024-11-14",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/live-podcast-unna-6u1dfm6uo2jq0",
      number: "Exklusiv #5",
      episode: "Live-Podcast Unna",
      timecode: 0,
      context: "zu Gast: Dirk Steffens",
      airDate: "2024-10-23",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/live-podcast-koeln-die-grosse-ueberraschung-fd8vbp81ih11w",
      number: "Exklusiv #3",
      episode: "Live-Podcast Köln: Die große Überraschung",
      timecode: 0,
      context: "zu Gast: Thomas Reunert",
      airDate: "2024-09-12",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/170-alles-ist-chemie-auch-hundepfoten-rng06s68gi49i",
      number: 170,
      episode: "Alles ist Chemie! Auch Hundepfoten",
      timecode: 0,
      context: "zu Gast: Dr. Mai Thi Nguyen-Kim",
      airDate: "2024-06-13",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/148-wald-jagd-mit-peter-wohlleben-hvjp782lct28v",
      number: 148,
      episode: "Wald & Jagd",
      timecode: 0,
      context: "zu Gast: Peter Wohlleben",
      airDate: "2024-01-11",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/142-missstaende-bei-tierversuchen-vtorqeruhl38m",
      number: 142,
      episode: "Missstände bei Tierversuchen",
      timecode: 0,
      context: "zu Gast: Dr. Kirsten Tönnies",
      airDate: "2023-11-30",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/140-vermittlungsaufruf-trainer-in-werden-mit-sophie-grethe-apxxickob7zpy",
      number: 140,
      episode: "Vermittlungsaufruf & Trainer:in werden",
      timecode: 0,
      context: "zu Gast: Sophie Grethe",
      airDate: "2023-11-16",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/137-der-weltmester-t27tks4vwyziw",
      number: 137,
      episode: "Der Weltmester",
      timecode: 0,
      context: "zu Gast: Mathias Mester",
      airDate: "2023-10-26",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/137-der-weltmester-t27tks4vwyziw",
      number: 137,
      episode: "Der Weltmester",
      timecode: 0,
      context: "zu Gast: Mathias Mester",
      airDate: "2023-10-26",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/127-podcast-live-ii-achterbahn-der-feelings-kk19bjk32yh1x",
      number: 127,
      episode: "Podcast live II: Achterbahn der Feelings",
      timecode: 0,
      context: "zu Gast: Detlev Steves und Carina Wingender",
      airDate: "2023-08-17",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/105-geiselnahme-skurrile-wildtiere-1-5-grad-waermer-9qzro9uynb4pc",
      number: 105,
      episode: "Geiselnahme, skurrile Wildtiere & 1,5 Grad wärmer",
      timecode: 0,
      context: "Gastbeitrag: Dr. Eckart von Hirschhausen",
      airDate: "2023-03-16",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/62-tierschutzhundeverordnung-strohhalmtest-zwingerhaltung-vbf1lpiq5foqn",
      number: 62,
      episode: "Tierschutzhundeverordnung, Strohhalmtest & Zwingerhaltung",
      timecode: 0,
      context: "Gastbeitrag: Dr. Sabine Holland",
      airDate: "2022-05-19",
    },
    {
      url: "https://plus.rtl.de/podcast/tierisch-menschlich-der-podcast-mit-hundeprofi-martin-ruetter-und-katharina-adick-m5iuweomug8fv/33-kastrieren-oder-nicht-nlz33543kmn6n",
      number: 33,
      episode: "Kastrieren oder nicht?",
      timecode: 0,
      context: "zu Gast: Dr. Ralf Unna",
      airDate: "2021-10-26",
    },
  ],
};

export default topic;
